kind: Service
apiVersion: v1
metadata:
  name: scdf-spring-cloud-dataflow-skipper
  labels:
    app.kubernetes.io/component: skipper
    app.kubernetes.io/instance: scdf
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: http
  selector:
      app.kubernetes.io/component: skipper
      app.kubernetes.io/instance: scdf
      app.kubernetes.io/name: spring-cloud-dataflow
