name: SCDF AT Kafka (Shepherd)

on:
  workflow_dispatch:
    inputs:
      cf-host:
        type: string
        description: 'CF host name (e.g. "note-1513782")'
        required: true
      tests:
        type: string
        description: 'Test classes'
        default: ''
  workflow_call:
    inputs:
      cf-host:
        type: string
        description: 'CF host name (e.g. "note-1513782")'
        required: true
      tests:
        type: string
        description: 'Test classes'
        default: ''
    secrets:
      CF_PASSWORD:
        required: true
      KAFKA_USERNAME:
        required: true
      KAFKA_PASSWORD:
        required: true
      KAFKA_BROKER_ADDRESS:
        required: true

jobs:
  acceptance-tests-kafka:
    uses: ./.github/workflows/at-common-workflow.yml
    with:
      cf_host: ${{ inputs.cf-host }}
      binder: kafka
      tests: ${{ inputs.tests }}
    secrets:
      CF_USERNAME: 'admin'
      CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
      KAFKA_USERNAME: ${{ secrets.KAFKA_USERNAME }}
      KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}
      KAFKA_BROKER_ADDRESS: ${{ secrets.KAFKA_BROKER_ADDRESS }}
