
name: SCDF AT for CF tile (Kafka - env 0)

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 0 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  kafka-0:
      uses: ./.github/workflows/common/at-common-workflow
      with:
          cf_host: alturas
          cf_index: 0
          binder: kafka

