
name: SCDF Acceptance Tests for CF tile

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 4 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  acceptance-tests:
    environment: scdf_at
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
       max-parallel: 3
       matrix:
         cf_host: ['santabarbara']
         binder: ['rabbit', 'kafka']
         include: 
            - cf_host: santabarbara
              db_index: 0
         
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: run the test script
        env:
          DEBUG: true
          SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SPACE : ${{ matrix.binder }}
          SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_PASSWORD: ${{ secrets.CF_ENV_0_PASSWORD }}
          # Postgres SQL Properties
          # SQL_DB_INDEX used as a suffix. Should be unique for each CF_HOST
          SQL_DB_INDEX: ${{ matrix.db_index }}
          SQL_HOST: ${{ secrets.SQL_HOST }}
          SQL_PORT: ${{ secrets.SQL_PORT }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          SQL_USERNAME: ${{ secrets.SQL_USERNAME }}
          JAVA_HOME: /opt/jdk-8
          DATAFLOW_TILE_KAFKA_BROKER_ADDRESS: ${{ secrets.KAFKA_BROKER_ADDRESS }}
          DATAFLOW_TILE_KAFKA_USERNAME: ${{ secrets.KAFKA_USERNAME }}
          DATAFLOW_TILE_KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}
          DEPLOY_PAUSE_TIME : 20
          CF_DIAL_TIMEOUT : 600
          JAVA_BUILDPACK : java_buildpack_offline
          PLATFORM : cloudfoundry
          PLATFORM_FOLDER : cloudfoundry-tile
          CERT_URI : "uaa.sys.${{ matrix.cf_host }}.cf-app.com"
          TRUST_CERTS : "api.sys.${{ matrix.cf_host }}.cf-app.com" 
          SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SKIP_SSL_VALIDATION : false
          SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_SERVICES : scdf-scheduler
          SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_URL : "https://api.sys.${{ matrix.cf_host }}.cf-app.com" 
          SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN : "apps.${{ matrix.cf_host }}.cf-app.com"
          SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_ORG : p-dataflow
          SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_USERNAME : ${{ secrets.CF_USERNAME }}
        run: |
           wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
           echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
           sudo apt-get update
           sudo apt-get install cf-cli
           scripts/at-test-script.sh
        
