name: SCDF AT Rabbit (Shepherd)

on:
  workflow_dispatch:
    inputs:
      cf-host:
        type: string
        description: 'CF host name (e.g. "note-1513782")'
        required: true
      tests:
        type: string
        description: 'Test classes'
        default: ''
  workflow_call:
    inputs:
      cf-host:
        type: string
        description: 'CF host name (e.g. "note-1513782")'
        required: true
      tests:
        type: string
        description: 'Test classes'
        default: ''
    secrets:
      CF_PASSWORD:
        required: true

jobs:
  acceptance-tests-rabbit:
    uses: ./.github/workflows/at-common-workflow.yml
    with:
      cf_host: ${{ inputs.cf-host }}
      binder: rabbit
      tests: ${{ inputs.tests }}
    secrets:
      CF_USERNAME: 'admin'
      CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
