name: SCDF AT Kafka - env 0

on:
  workflow_dispatch:
    inputs:
      tests:
        type: string
        default: ''
        description: 'Test classes'
  workflow_call:
    inputs:
      tests:
        type: string
        default: ''
        description: 'Test classes'
    secrets:
      CF_USERNAME:
        required: true
      CF_ENV_0_PASSWORD:
        required: true
      CF_ENV_1_PASSWORD:
        required: true
      CF_ENV_2_PASSWORD:
        required: true
      SQL_USERNAME:
        required: false
      SQL_PASSWORD:
        required: false
      SQL_SYSTEM_USERNAME:
        required: false
      SQL_SYSTEM_PASSWORD:
        required: false
      SQL_HOST:
        required: false
      SQL_PORT:
        required: false
      KAFKA_USERNAME:
        required: false
      KAFKA_PASSWORD:
        required: false
      KAFKA_BROKER_ADDRESS:
        required: false

jobs:
  kafka-0:
    uses: ./.github/workflows/at-common-workflow.yml
    with:
      cf_host: bucharest
      cf_index: 0
      binder: kafka
      tests: ${{ inputs.tests }}
    secrets:
      CF_USERNAME: ${{secrets.CF_USERNAME}}
      CF_ENV_0_PASSWORD: ${{secrets.CF_ENV_0_PASSWORD}}
      CF_ENV_1_PASSWORD: ${{secrets.CF_ENV_1_PASSWORD}}
      CF_ENV_2_PASSWORD: ${{secrets.CF_ENV_2_PASSWORD}}
      SQL_USERNAME: ${{secrets.SQL_USERNAME}}
      SQL_PASSWORD: ${{secrets.SQL_PASSWORD}}
      SQL_SYSTEM_USERNAME: ${{secrets.SQL_USERNAME}}
      SQL_SYSTEM_PASSWORD: ${{secrets.SQL_PASSWORD}}
      SQL_HOST: ${{secrets.SQL_HOST}}
      SQL_PORT: ${{secrets.SQL_PORT}}
      KAFKA_USERNAME: ${{secrets.KAFKA_USERNAME}}
      KAFKA_PASSWORD: ${{secrets.KAFKA_PASSWORD}}
      KAFKA_BROKER_ADDRESS: ${{secrets.KAFKA_BROKER_ADDRESS}}
