
name: SSCDF AT for CF tile (Kafka - env 2)

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 8 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    kafka-2:
        uses: ./.github/workflows/common/at-common-workflow
          with:
            cf_host: benicia
            cf_index: 2
            binder: kafka
