
name: SCDF AT Kafka env 1

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 4 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
   kafka-1:
    uses: ./.github/workflows/common/at-common-workflow
    with:
        cf_host: avenal
        cf_index: 1
        binder: kafka
