
name: SCDF AT Kafka - env 2

# Controls when the workflow will run
on:
  #schedule:
  #- cron: "0 8 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    kafka-2:
        uses: ./.github/workflows/at-common-workflow.yml
        with:
            cf_host: benicia
            cf_index: 2
            binder: kafka
        secrets:
            CF_USERNAME: ${{secrets.CF_USERNAME}}
            CF_ENV_0_PASSWORD: ${{secrets.CF_ENV_0_PASSWORD}}
            CF_ENV_1_PASSWORD: ${{secrets.CF_ENV_1_PASSWORD}}
            CF_ENV_2_PASSWORD: ${{secrets.CF_ENV_2_PASSWORD}}
            SQL_USERNAME: ${{secrets.SQL_USERNAME}}
            SQL_PASSWORD: ${{secrets.SQL_PASSWORD}}
            SQL_HOST: ${{secrets.SQL_HOST}}
            SQL_PORT: ${{secrets.SQL_PORT}}
            SQL_SYSTEM_USERNAME: ${{secrets.SQL_USERNAME}}
            SQL_SYSTEM_PASSWORD: ${{secrets.SQL_PASSWORD}}
            KAFKA_USERNAME: ${{secrets.KAFKA_USERNAME}}
            KAFKA_PASSWORD: ${{secrets.KAFKA_PASSWORD}}
            KAFKA_BROKER_ADDRESS: ${{secrets.KAFKA_BROKER_ADDRESS}}
