
name: SCDF AT Rabbit - env 0

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 4 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    rabbit-0:
        uses: ./.github/workflows/at-common-workflow.yml
        with:
             environment : scdf_at
             cf_host: alturas
             cf_index: 0
             binder: rabbit
