# This is a test
name: Experiment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# Controls when the workflow will run
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  experiment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
        CF_USERNAME: ${{secrets.CF_USERNAME}}
        CF_ENV_0_PASSWORD: ${{secrets.CF_ENV_0_PASSWORD}}
        CF_ENV_1_PASSWORD: ${{secrets.CF_ENV_1_PASSWORD}}
        CF_ENV_2_PASSWORD: ${{secrets.CF_ENV_2_PASSWORD}}
        SQL_PROVIDER: oracle
        SQL_USERNAME: ${{secrets.ORACLE_USERNAME}}
        SQL_PASSWORD: ${{secrets.ORACLE_PASSWORD}}
        SQL_HOST: ${{secrets.ORACLE_HOST}}
        SQL_PORT: ${{secrets.ORACLE_PORT}}
        BINDER: rabbit
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Runs a single command using the runners shell
      - name: run some commands
        run: |
            #Install required POSTGRESQL lib for python
            PATH=$PATH:~/.local/bin
            python3 -m pip install --upgrade pip
            pip3 install psycopg2-binary
            #Install required ORACLE lib for python
            pip3 install cx_Oracle --upgrade --user
            #Install cf cli
            os=$(uname)
             if [[ "$os"=="Linux" ]]; then
              if [[ "$SQL_PROVIDER"=="oracle" ]]; then
                echo "Installing ORACLE components"
                #sudo apt-get install build-essential unzip python-dev libaio-dev
                wget -q -O - https://download.oracle.com/otn_software/linux/instantclient/215000/instantclient-basiclite-linux.x64-21.5.0.0.0dbru.zip
                export LD_LIBRARY_PATH=./instantclient_21_5
              fi
            fi
            python3 ./cloudfoundry-tile/server/config_service_instance.py



