name: Acceptance Tests for SCDF

on:
  schedule:
    # 4:00 UTC Mon - Fri
    - cron: "0 4 * * 1-5"
  workflow_dispatch:
    inputs:
      tests:
        type: string
        default: ''
        description: 'Test classes'

jobs:
  kafka-0:
    uses: ./.github/workflows/acceptance-tests-for-kafka-0.yml
    with:
      tests: ${{ inputs.tests }}
    secrets:
      CF_USERNAME: ${{ secrets.CF_USERNAME }}
      CF_ENV_0_PASSWORD: ${{ secrets.CF_ENV_0_PASSWORD }}
      CF_ENV_1_PASSWORD: ${{ secrets.CF_ENV_1_PASSWORD }}
      SQL_USERNAME: ${{ secrets.SQL_USERNAME }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      SQL_SYSTEM_USERNAME: ${{ secrets.SQL_USERNAME }}
      SQL_SYSTEM_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      SQL_HOST: ${{ secrets.SQL_HOST }}
      SQL_PORT: ${{ secrets.SQL_PORT }}
      KAFKA_USERNAME: ${{ secrets.KAFKA_USERNAME }}
      KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}
      KAFKA_BROKER_ADDRESS: ${{ secrets.KAFKA_BROKER_ADDRESS }}
  rabbit-1:
    uses: ./.github/workflows/acceptance-tests-for-rabbit-1.yml
    with:
      tests: ${{ inputs.tests }}
    secrets:
      CF_USERNAME: ${{ secrets.CF_USERNAME }}
      CF_ENV_0_PASSWORD: ${{ secrets.CF_ENV_0_PASSWORD }}
      CF_ENV_1_PASSWORD: ${{ secrets.CF_ENV_1_PASSWORD }}
      SQL_USERNAME: ${{ secrets.SQL_USERNAME }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      SQL_SYSTEM_USERNAME: ${{ secrets.SQL_USERNAME }}
      SQL_SYSTEM_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      SQL_HOST: ${{ secrets.SQL_HOST }}
      SQL_PORT: ${{ secrets.SQL_PORT }}
  kafka-1:
    needs: [ rabbit-1 ]
    uses: ./.github/workflows/acceptance-tests-for-kafka-1.yml
    with:
      tests: ${{ inputs.tests }}
    secrets:
      CF_USERNAME: ${{ secrets.CF_USERNAME }}
      CF_ENV_0_PASSWORD: ${{ secrets.CF_ENV_0_PASSWORD }}
      CF_ENV_1_PASSWORD: ${{ secrets.CF_ENV_1_PASSWORD }}
      SQL_USERNAME: ${{ secrets.SQL_USERNAME }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      SQL_SYSTEM_USERNAME: ${{ secrets.SQL_USERNAME }}
      SQL_SYSTEM_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      SQL_HOST: ${{ secrets.SQL_HOST }}
      SQL_PORT: ${{ secrets.SQL_PORT }}
      KAFKA_USERNAME: ${{ secrets.KAFKA_USERNAME }}
      KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}
      KAFKA_BROKER_ADDRESS: ${{ secrets.KAFKA_BROKER_ADDRESS }}
  rabbit-0:
    needs: [ kafka-0 ]
    uses: ./.github/workflows/acceptance-tests-for-rabbit-0.yml
    with:
      tests: ${{ inputs.tests }}
    secrets:
      CF_USERNAME: ${{ secrets.CF_USERNAME }}
      CF_ENV_0_PASSWORD: ${{ secrets.CF_ENV_0_PASSWORD }}
      CF_ENV_1_PASSWORD: ${{ secrets.CF_ENV_1_PASSWORD }}
      SQL_USERNAME: ${{ secrets.SQL_USERNAME }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      SQL_SYSTEM_USERNAME: ${{ secrets.SQL_USERNAME }}
      SQL_SYSTEM_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      SQL_HOST: ${{ secrets.SQL_HOST }}
      SQL_PORT: ${{ secrets.SQL_PORT }}
  completed:
    needs: [ kafka-0, rabbit-0, kafka-1, rabbit-1 ]
    runs-on: ubuntu-latest
    steps:
      - name: Completed
        run: echo "Completed"
